name: blog_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.0
  flutter_bloc: ^7.3.1
  cloud_firestore: ^1.0.5
  rxdart: ^0.27.0
  firebase_core: ^1.0.3
  uuid: ^3.0.4
  json_serializable: ^4.1.0
  logger: ^1.0.0
  firebase_auth: "^3.1.3"
  flutter_sizer: ^1.0.4
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:

flutter:

  uses-material-design: true

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Bold.otf
          weight: 700